### ISSUE TITLE
Uploading large files from a stream

### ISSUE THREAD

**Issue by ghazi-git** [cloudinary/pycloudinary#120]
Hello,

I've been using cloudinary for quite some time and it's been great. Thanks.

Now, I need to be able to upload large files (generated reports) that might go beyond 100 MB. According to docs, I need to use the [upload_large](http://cloudinary.com/documentation/upload_images#chunked_image_upload). My issue is that I have a stringio object and I couldn't use the upload_large function to upload it to cloudinary (stringio object worked fine with cloudinary.uploader.upload). I'm getting this:
`TypeError: coercing to Unicode: need string or buffer, instance found`
Looking at the [implementation of upload_large](https://github.com/cloudinary/pycloudinary/blob/master/cloudinary/uploader.py#L60), I see that it's invoking `open` on the file argument which means it expects a filename/path of a file on the file system which is inconsistent compared to cloudinary.uploader.upload.

So, I want to ask:
- Is there a way to use a stream (maybe sth other than stringio) with `upload_large` ?
- Also, I want to check if there is a constraint that needs the "large" files to be on the file system.

Of course I have no file size issue as the paid cloudinary plan is customized to support uploading up to 200MB per file.

Thank you.

**Comment by MaorGariv** [comment]
Hi @ghazi-git,

Thanks for reporting this issue. I went ahead and opened a feature request for this issue. Our SDK team is currently checking this issue. 

Thanks,
Maor
