### ISSUE TITLE
Text Overlay in another language ( Unicode encoding error ) 

### ISSUE THREAD

**Issue by codeAshu** [cloudinary/pycloudinary#122]
I am building text overlay on different languages. I am getting Unicode encoding error. 
Here is my code - https://gist.github.com/codeAshu/8b9c588d02792424f44057a98c8edf2a

Error trace - 
`
{"overlay": text, "color": "yellow", "crop": "fit", "width": 300, "height": 250}, File "/base/data/home/apps/s~pfpibot/v1.404212240051032763/lib/cloudinary/__init__.py", line 211, in image src, attrs = self.__build_url(**options) File "/base/data/home/apps/s~pfpibot/v1.404212240051032763/lib/cloudinary/__init__.py", line 197, in __build_url return utils.cloudinary_url(public_id, **combined_options) File "/base/data/home/apps/s~pfpibot/v1.404212240051032763/lib/cloudinary/utils.py", line 397, in cloudinary_url transformation, options = generate_transformation_string(**options) File "/base/data/home/apps/s~pfpibot/v1.404212240051032763/lib/cloudinary/utils.py", line 99, in generate_transformation_string base_transformations = list(map(recurse, base_transformations)) File "/base/data/home/apps/s~pfpibot/v1.404212240051032763/lib/cloudinary/utils.py", line 96, in recurse return generate_transformation_string(**bs)[0] File "/base/data/home/apps/s~pfpibot/v1.404212240051032763/lib/cloudinary/utils.py", line 198, in generate_transformation_string sorted_params = sorted([param + "_" + str(value) for param, value in params.items() if (value or value == 0)])
`

**Comment by d-mendoza** [comment]
Hello @codeAshu,

I would like to apologize for the delay.

To better diagnose the issue, can you provide us with the following: (1) an example of the text you are passing in and (2) the URL response from your code. 

Thanks

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
