### ISSUE TITLE
Update `_get_val_from_object` method

### ISSUE THREAD

**Issue by dbinetti** [cloudinary/pycloudinary#131]
The `_get_val_from_object` method has been renamed in Django 2.0 to `value_from_object`.  This affects https://github.com/cloudinary/pycloudinary/blob/master/cloudinary/models.py#L46. I'm actually not sure about the pattern for version conditional checks, otherwise I'd submit a patch....

**Comment by roeeba** [comment]
Hi @dbinetti. Apologies for the late response. Thank you for reporting this. I've opened a ticket with our dev team. We'll update as soon as this is resolved.

**Comment by dbinetti** [comment]
thanks, prognosis @roeeba ?

**Comment by roeeba** [comment]
Hi @dbinetti. A fix has already been implemented in our master branch. It will be released with the next version.

**Comment by dbinetti** [comment]
👍

**Comment by roeeba** [comment]
Hi @dbinetti, the fix has been deployed.
