### ISSUE TITLE
Image upload not working in ubuntu 16.04 but works in windows 10

### ISSUE THREAD

**Issue by snbhanja** [cloudinary/pycloudinary#144]
Hi 

My python script tries to upload a image, but I am getting below error. Please help.
output_image = "abcd.jpg"
**cloudinary.uploader.upload(output_image)**

The error as below,
Traceback (most recent call last):
  File "face_detect4.py", line 31, in <module>
    cloudinary.uploader.upload(output_image)
  File "/usr/local/lib/python2.7/dist-packages/cloudinary/uploader.py", line 40, in upload
    return call_api("upload", params, file=file, **options)
  File "/usr/local/lib/python2.7/dist-packages/cloudinary/uploader.py", line 303, in call_api
    response = _http.request("POST", api_url, param_list, headers, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 73, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 162, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 482: ordinal not in range(128)Te

**Comment by roeeba** [comment]
Hi @snbhanja. To better understand the issue, can you please share with us the code causing the error and the original file you're trying to upload? if you rather keep it confidential, please feel free to open a support ticket at support@cloudinary.com and share the details there.

**Comment by snbhanja** [comment]
Hi @roeeba.
I am trying this simple code to upload the image face4.jpeg

import json
import cloudinary
import cloudinary.uploader
import cloudinary.api

data = json.loads('{"cloud_name":"xxxx","api_key":"xxxx","api_secret":"xxxx"}')

# Setup cloudinary configuration.
cloudinary.config( 
  cloud_name = data["cloud_name"], 
  api_key = data["api_key"], 
  api_secret = data["api_secret"] 
)

cloudinary.uploader.upload("face4.jpeg")

**Comment by roeeba** [comment]
Thanks, @snbhanja. Could you please also share the actual file ('face4.jpeg')?

**Comment by snbhanja** [comment]
![face4](https://user-images.githubusercontent.com/3896278/37716130-c5fe6e86-2d43-11e8-8604-58d1ac39ea75.jpg)

**Comment by snbhanja** [comment]
Sorry for the dely.
Here is the image [https://imgur.com/a/A5s6P](url)

**Comment by roeeba** [comment]
Hi @snbhanja. The link seems to be broken. I get to a 404 page.

**Comment by snbhanja** [comment]
this works,

https://drive.google.com/open?id=1M-Ddgfrer3ov2-ZZNcX1-V2SdJECMRZj

**Comment by idobarnoam** [comment]
Hi @snbhanja,

Are you uploading the image from a local path or are you using fetching the image directly from the google drive address supplied?

I'm asking since uploading the image from a local path works correctly on my end.

Could you maybe share additional information on how are making the upload call, and how are you getting the image from Google drive?

**Comment by snbhanja** [comment]
Hi,

I am uploading the image from local path, not from Google drive.
Somehow I am getting the encoding error. The default python version is 2.7
in Ubuntu in a Google cloud platform vm. and I am using the same.

Could you please tell me what python version it is working?

**Comment by idobarnoam** [comment]
The python version I am using is 2.7.13

I've downloaded the image you shared on the drive and performed the below call:

`cloudinary.uploader.upload("/path/to/image/face4.jpeg")`

and received a correct response, and made sure the image was uploaded.

Are you experiencing this with other images?
Could you share the exact call you are making to perform the upload?

Also, if you prefer its possible to open a request at support@cloudinary.com so we could take a closer look at your request.

**Comment by giyama** [comment]
I`m facing the same issue. I noticed that it happens only when I try to upload from local path.

**Comment by giyama** [comment]
I managed to get it working by running the script inside python shell, then I realised what was messing my code was this line `from __future__ import unicode_literals`.

**Comment by idobarnoam** [comment]
@giyama Glad to hear its working.

Could you elaborate on what was the issue and what you did yo handle it?

This would help the community in us in pinpointing future cases, and make the necessary changes.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
