### ISSUE TITLE
transformation in django upon upload not working

### ISSUE THREAD

**Issue by bukowa** [cloudinary/pycloudinary#190]
I am using your example django project, this is what i added (copied from docs):
But image is not transformed after uploading with direct upload. Why? It works normal with server-side upload using same 'options'...

````python
class PhotoDirectForm(PhotoForm):
    image = CloudinaryJsFileField(
        attrs={'style': "margin-top: 30px"},
        options={
            'tags': "directly_uploaded",
            'crop': 'limit', 'width': 1000, 'height': 1000,
            'eager': [{'crop': 'fill', 'width': 150, 'height': 100}]
        })
````

**Comment by idobarnoam** [comment]
@bukowa could you share additional details regarding the use case?
What are the python, django versions you are using
How are you performing the upload?
Where was this added?

**Comment by ivanvenosdel** [comment]
I have the same problem and also doesn't seem to apply the tags. Python3.6 and Django 1.11.

**Comment by ivanvenosdel** [comment]
As for additional direct uploading options, that is also in the [cloudinary docs](https://cloudinary.com/documentation/django_image_and_video_upload#additional_direct_uploading_options) but, as stated, the options don't seem to apply.

**Comment by idobarnoam** [comment]
Thanks, @ivanvenosdel.

We confirmed this n versions 1.11.

We have opened a request with our dev team to look into this.

We would update this thread with any insights when they occur.

**Comment by ivanvenosdel** [comment]
@idobarnoam If it helps, I have done extensive debugging trying to figure out a work around and it seems like the options get lost after the point where they are passed to CloudinaryInput widget. I think this is because when render is called on that widget the options in self.attrs are not merged into the local attrs variable (and therefore ignored).

**Comment by bukowa** [comment]
I were using 2.x

**Comment by idobarnoam** [comment]
@ivanvenosdel Thanks for investigation - it helps!
@bukowa Thanks for the additional information.

We are looking into this and when there are any new insights we would update the thread.

**Comment by ivanvenosdel** [comment]
Works for me in Django 1.11x.

**Comment by idobarnoam** [comment]
Thanks for confirming @ivanvenosdel!
