### ISSUE TITLE
Chained Transformations in python

### ISSUE THREAD

**Issue by fc373745** [cloudinary/pycloudinary#193]
Currently i have a url like so 
```
url = cloudinary_url(upload_result["public_id"], format="jpg", width=450, quality="auto:good")[0]
```

If i want to make a chained transformation of scaling it down to a width of 900px and then cropping a width of 450px, padded left by 225px how would i go about doing that?

the url I want to buld is like so

```
https://res.cloudinary.com/dg8szh4ec/image/upload/w_900/c_crop,x_225,w_450/v1555281517/jfnj4pqbtk5dn0lzfper.jpg
```

HOWEVER, the image that is brought back, the height is also cropped for some reason where i want it to be 100 percent of the height `h_1.0` gives me an error if i add it to the url

How would i get this chained transformation using the `cloudinary_url` function? The documentation uses other methods dealing withe chained transformations.

Also how do i make sure i get the height back at 100%?

**Comment by brian-cloudinary** [comment]
You can use variables in your URLs - `ih` would refer to the original height of the image:

```
https://res.cloudinary.com/dg8szh4ec/image/upload/$h_ih/w_900/c_crop,x_225,w_450/h_$h/jfnj4pqbtk5dn0lzfper.jpg
```

Generating a Cloudinary URL with chained transformations can be done by passing the transformation as a list of dictionaries in the `transformation` keyword argument.

```
url = cloudinary_url('jfnj4pqbtk5dn0lzfper', transformation=[{"$h": "ih"}, {"width": 900}, {"crop": "crop", "x": 225, "width": 450}, {"height": "$h"}])[0]
```
