### ISSUE TITLE
New version 1.18.0 requires CLOUDINARY_API_PROXY environment variable to exist

### ISSUE THREAD

**Issue by ejucovy** [cloudinary/pycloudinary#217]
My pycloudinary applications are all failing if I upgrade to 1.18.0 --

https://github.com/cloudinary/pycloudinary/commit/56570ee625104853f47039c9dc8c5b514dd10d64#diff-9668999067e1e17a9985c93999f2357cR108

Shouldn't that be `api_proxy=os.environ.get("CLOUDINARY_API_PROXY")`?

**Comment by const-cloudinary** [comment]
@ejucovy Thank you for reporting the issue, please try new 1.18.1 version

**Comment by ejucovy** [comment]
That worked, thanks!
