### ISSUE TITLE
how to upload a mp4 file

### ISSUE THREAD

**Issue by nocb** [cloudinary/pycloudinary#219]
i upload a  mp4 file 
 `cloudinary.exceptions.Error: Invalid image file,`

**Comment by nocb** [comment]
sorry , i see  ,how to upload   
resource_type = "video",

**Comment by aleksandar-cloudinary** [comment]
Hi @nocb . Yes, the default resource_type is set to 'image' so if you weren't passing it explicitly then that would be why. There is also the 'auto' resource_type where you don't have to set that manually (image/video or raw) and Cloudinary will automatically detect what type of file it is and use the correct resource_type.

**Comment by aleksandar-cloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
