### ISSUE TITLE
Mock library in setup.py install_requires

### ISSUE THREAD

**Issue by mloo-sp** [cloudinary/pycloudinary#220]
Mock is only used for testing.  Please consider moving it to setup.py test_requires.

**Comment by roeeba** [comment]
Hi @mloo-sp. Thanks for pointing this out. We'll make sure to fix that.

**Comment by milind-shakya-sp** [comment]
@roeeba would you mind taking a look at https://github.com/cloudinary/pycloudinary/pull/227 which attempts to fix this issue?

**Comment by roeeba** [comment]
Hi @milind-shakya-sp. Thank you for your contribution. Our engineers will look at it and will update.

**Comment by roeeba** [comment]
This issue was fixed on a later version of the library.
