### ISSUE TITLE
metadata argument ignored during upload

### ISSUE THREAD

**Issue by yktoo** [cloudinary/pycloudinary#221]
According to [docs](https://cloudinary.com/documentation/image_upload_api_reference#upload_method), you can supply the `metadata` argument to `cloudinary.uploader.upload()` to add custom metadata to the uploaded image:

> metadata | String | A map (using the SDKs) or pipe-separated list (for direct API calls) of custom metadata fields

However this option doesn't seem to be used anywhere in the API, and the uploaded images do not get any metadata associated.

Sample code:

```python
cloudinary.uploader.upload(
                file_path,
                public_id=file_id,
                folder='blog',
                resource_type='image',
                metadata={'url': original_url})
```

**Comment by brian-cloudinary** [comment]
Hi @yktoo, the Structured Metadata feature is relatively new, and we're in the process of implementing its functionality in our Python SDK.

I'd be happy to let you know when this is done!

**Comment by yktoo** [comment]
Is it an idea to mention that in the docs?

Currently I've worked around this by using `context=` instead of `metadata=`, the result appears to be the same.

**Comment by roeeba** [comment]
Hi @yktoo. I agree we should have mentioned that in our docs. I will open a ticket for the relevant team. 
We will update here once structured metadata is supported in the Python SDK.

**Comment by roeeba** [comment]
Fixed on - https://github.com/cloudinary/pycloudinary/pull/226
