### ISSUE TITLE
How to set the upload directory? using django cloudinary field?

### ISSUE THREAD

**Issue by abkiran** [cloudinary/pycloudinary#228]
I used Django package `cloudinary==1.19.1`

`models.py`
```
class Category(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    background_image = CloudinaryField(null=True, folder='01-categories/')
```

When I upload the image from Django admin change form, it is being uploaded to the root of cloudinary,

I want the image to be uploaded to `01-categories/`.

Anyone please let me know how to achieve that.
@brian-cloudinary @cloudinary @CloudinaryLtd

**Comment by brian-cloudinary** [comment]
@abkiran Based on our [documentation](https://cloudinary.com/documentation/image_upload_api_reference#optional_parameters), you can pass the `folder` parameter to the `upload` method.

```
cloudinary.uploader.upload("myfile.jpg", folder="01-categories")
```

You can also specify parameters to be passed to the `upload` method in `CloudinaryFileField` via the `options` parameter. From the [docs](https://cloudinary.com/documentation/django_image_and_video_upload#django_forms_and_models):

```
from django.forms import ModelForm      
from cloudinary.forms import CloudinaryFileField      
from .models import Photo

class PhotoForm(ModelForm):
  class Meta:
    model = Photo
  image = CloudinaryFileField(
    options = { 
      'folder': '01-categories'
    })
```
