### ISSUE TITLE
Support Cloudinary for latest version of Django

### ISSUE THREAD

**Issue by Naveen-Malineni** [cloudinary/pycloudinary#241]
# Feature request for Cloudinary Python SDK
Please provide support for newer version of Django

## Explain your use case
After installation & Integration of cloudinary library...It is not supporting new version of Djano...
i have an issue...by default site-packages\cloudinary\templates\cloudinary_includes.html
having {% load staticfiles %} but it is not supported by Django new version... 
## Describe the problem you’re trying to solve
i would like to integrate Cloudinary to latest version of Django
## Do you have a proposed solution?
… (yes, no? Please elaborate if needed)
yes, need to change {% load staticfiles %} as {% load static %}...

**Comment by roeeba** [comment]
Hi @Naveen-Malineni Thank you for pointing this out. I've opened an internal ticket to our engineers. We'll update here once ready.
