### ISSUE TITLE
Stuck when uploading video through CloudinaryField in admin

### ISSUE THREAD

**Issue by jf-cucalon** [cloudinary/pycloudinary#255]
Hi, whenever i try to upload a video through the django admin interface using the cloudinaryfield it just gets stuck processing forever, What am i doing wrong ?

**Comment by jf-cucalon** [comment]
or does the upload_large method return a url so i can save it to a charfield in my database

**Comment by shirlymanor** [comment]
@jf-cucalon the best way to get a notification on async upload is using notification URL. If you are using eager transformation (recommended) you can add the eager_notification_url.
If that doesn't work, please open a ticket to support@cloudinary.com with your cloud name that we can look at your code.
