### ISSUE TITLE
How do I delete the "raw" resource ?

### ISSUE THREAD

**Issue by a-n-s** [cloudinary/pycloudinary#260]
I have a add-on "aspose" for converting raw resource to pdf. So when I delete the raw resource the pdf one also should get deleted. How do I achieve that?

**Comment by Vdeub-cloudinary** [comment]
Hi @adityashanbhog 

When using the Aspose Add-On, it generates a PDF which has the `resource_type:image` whereas the file uploaded has the `resource_type:raw`, hence you can run a deletion with those 2 types like this: 

To delete the raw file in Python:

`cloudinary.uploader.destroy('p5sxi8s04oiueembnt5k.xls', resource_type = 'raw')`

To delete the PDF created via Aspose in Python:

`cloudinary.uploader.destroy('p5sxi8s04oiueembnt5k.xls')`

**Comment by a-n-s** [comment]
@Vdeub-cloudinary  Thanks for the response.
