### ISSUE TITLE
How can I pass variable in image template tag?

### ISSUE THREAD

**Issue by umutambyi-gad** [cloudinary/pycloudinary#270]
I have problem with an image template tag where I can't pass variable once I pass a variable it rendered out as it is without being processed let me give an example with code
```
<img src="profile.image.url" alt="{{ profile.user.get_full_name }}'s profile image" />
```
the above code will give the following result when there is a problem with an image or may be less connection

![expected](https://user-images.githubusercontent.com/65312850/108390043-8d43b500-7210-11eb-8119-6ceb418565b5.PNG)

but when I use cloudinary image template tag like
```
{% cloudinary profile.image.url alt="{{ profile.user.get_full_name }}'s profile image " %}
```
the following is unexpected output

![issue](https://user-images.githubusercontent.com/65312850/108390703-38546e80-7211-11eb-8779-1a293c891132.PNG)

Thanks in advanced

**Comment by d-mendoza** [comment]
@umutambyi-gad When using the template tag, can you try the following structure:

{% cloudinary profile.image.url alt=profile.user.get_full_name %}

This should do the trick as the variable **profile.user.get_full_name** gets evaluated as a string.

**Comment by umutambyi-gad** [comment]
Nice trick it works. thanks a lot
