### ISSUE TITLE
CloudinaryField video - not using upload_large chunks for 100mb video file

### ISSUE THREAD

**Issue by northkode** [cloudinary/pycloudinary#279]
## Bug report for Cloudinary Python SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
Using chunked uploads with CloudinaryField resource_type='video'

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ X] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
It doesnt seem to call the upload_large call on the CloudinaryField if the file type is large there for running into memory issues uploading 100+mb files

## Operating System
[X ] Linux
[ ] Windows
[ ] OSX
[ ] All

## Environment and Frameworks (fill in the version numbers)
Cloudinary Python SDK version - Latest
Python Version - 3.6
Django - 3.2.1

**Comment by roeeba** [comment]
Hi @northkode, Can you please share the code you're using that reproduces the issue? Any error messages you can share as well? Thanks

**Comment by roeeba** [comment]
Hi @northkode, I've been just informed that this is a known issue which we're currently working on. We'll update here once fixed.

**Comment by const-cloudinary** [comment]
Fixed in #284
