### ISSUE TITLE
Add support for pathlib.Path

### ISSUE THREAD

**Issue by jarekwg** [cloudinary/pycloudinary#282]
# Feature request for Cloudinary Python SDK
`pathlib` is the modern way of dealing with paths in Python. Cloudinary should accept `Path` objects as input.
Django itself recently made a nice move in this direction: https://code.djangoproject.com/ticket/28428

## Explain your use case
We're using Path objects in our codebase and are finding we have to cast them to `str` prior to interacting with cloudinary.

## Describe the problem you’re trying to solve
When paths are concerned, raw string manipulation, is oft messy and error prone. Here's an example:
https://github.com/cloudinary/pycloudinary/blob/fe95df18967e8fb50d97c40bfaedb0386866c698/cloudinary/__init__.py#L282-L294
Pathlib offers a neat way of handling this. Let's not punish people trying to do the right thing and let them pass `Path` objects into this lib if they're using them already.

## Do you have a proposed solution?
Yep, minimal solution is to allow `Path` objects to be passed in as parameters as well as strings. All that needs to change is you call `str()` on any incoming path, then can continue handling as strings internally.
More involved solution would be to embrace `pathlib` internally; though this'd be best done after dropping python 2 support.

**Comment by Vdeub-cloudinary** [comment]
Hi @jarekwg,

Thanks for reporting this. 
I have opened a feature request internally to support this in the future.

At this point in time, we won't have any ETA to share.

Thank you for your understanding and patience in this matter.

Kind regards,
Loic
