### ISSUE TITLE
AttributeError: module 'cloudinary' has no attribute 'uploader'

### ISSUE THREAD

**Issue by aliisakroe** [cloudinary/pycloudinary#287]
## Bug report for Cloudinary Python SDK
Before proceeding, please update to the latest version and test if the issue persists

## Describe the bug in a sentence or two.

Package does not seem to include basic upload object? This is a completely blocking behavior. Has anyone else seen this issue? 

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots or Stack Trace (if applicable)

cloudinary.uploader.upload('vid.mp4', **options)
AttributeError: module 'cloudinary' has no attribute 'uploader'

## Operating System
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)

- Cloudinary Python SDK version - 1.26.0
- Python Version - 0.0.0 
- Framework (Django, Flask, etc) - 0.0.0

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by momoip** [comment]
Hi,
Thanks for reaching out.
Please add `import cloudinary.uploader` to use the uploader.
Thanks,
Mo

**Comment by aliisakroe** [comment]
I see it is in the ask docs now. Thank you for your response.

**Comment by momoip** [comment]
That's great.  
Please let us know if you have any other questions.
Mo
