### ISSUE TITLE
Regression in Cloudinary 1.26.0 "ValueError: embedded null byte" when using `upload_resource`

### ISSUE THREAD

**Issue by levinotik** [cloudinary/pycloudinary#293]
## Bug report for Cloudinary Python SDK
Before proceeding, please update to the latest version and test if the issue persists

## Describe the bug in a sentence or two.

New regression in version 1.26.0. Using `cloudinary.uploader.upload_resource` results in

```bash
file_io = open(file, 'rb')
ValueError: embedded null byte
```

Same code works fine when reverting to cloudinary 1.25.0
…

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [X] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
Retrieve bytes of an image and then pass to `cloudinary.uploader.upload_resource`. Results in 

```
Traceback (most recent call last):
  File "/Users/levinotik/dev/gj/control/control/turns/tasks/sync_photos_from_foto_notes.py", line 58, in set_cloudinary_image
    photo.image = cloudinary.uploader.upload_resource(response)
  File "/Users/levinotik/dev/gj/control/.venv/lib/python3.8/site-packages/cloudinary/uploader.py", line 61, in upload_resource
    result = upload_large(file, **options)
  File "/Users/levinotik/dev/gj/control/.venv/lib/python3.8/site-packages/cloudinary/uploader.py", line 76, in upload_large
    file_io = open(file, 'rb')
ValueError: embedded null byte
```

## Error screenshots or Stack Trace (if applicable)
…

## Operating System
- [X] Linux
- [ ] Windows
- [X ] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)

- Cloudinary Python SDK version - 1.26.0
- Python Version - Python 3.8.6 
- Framework (Django, Flask, etc) - 0.0.0

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by levinotik** [comment]
Any movement on this? Would be great to upgrade our dependency. As of now we cannot use cloudinary > 1.25.0

**Comment by momoip** [comment]
I'm checking internally and will update you the status once I get some insights.

**Comment by const-cloudinary** [comment]
Hi @levinotik , the issue should be fixed in:
https://github.com/cloudinary/pycloudinary/releases/tag/1.28.0

**Comment by levinotik** [comment]
Fantastic, thanks a lot!
