### ISSUE TITLE
Can't get it to work in Flask

### ISSUE THREAD

**Issue by tylerwaitt** [cloudinary/pycloudinary#30]
I load in all my settings in Flask.  But I keep getting this error:

    django.core.exceptions.ImproperlyConfigured: Requested settings, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
