### ISSUE TITLE
Since update to latest, uploading any file(large or small) takes forever and now my server times out

### ISSUE THREAD

**Issue by northkode** [cloudinary/pycloudinary#301]
## Bug report for Cloudinary Python SDK
Before proceeding, please update to the latest version and test if the issue persists

## Describe the bug in a sentence or two.
…

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [X ] Performance - Performance issues
- [ ] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
uploading file with CloudinaryField(resource_type="video")
uploads are taking forever and they are causing my server (with a nginx timeout of 300) to crash. This never used to happen

i have tried all sorts of server configs to no avail, only conclusion I can come up with is something in this library changed and the chunk sizes or something isnt working. Even uploading a 20mb file crashes.. when i used to be able to upload 500mb + with same server configs 

## Error screenshots or Stack Trace (if applicable)
…

## Operating System
- [X ] Linux
- [ ] Windows
- [ ] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)

- Cloudinary Python SDK version - 1.2.6
- Python Version - 3.6 
- Framework (Django, Flask, etc) - 3

**Comment by epasos573** [comment]
@northkode As we will need to get additional information from you in order to further investigate this case, may I request to raise a support ticket through https://support.cloudinary.com/hc/en-us/requests/new.
