### ISSUE TITLE
Django and upload_preset config

### ISSUE THREAD

**Issue by Hecsall** [cloudinary/pycloudinary#302]
# Feature request for Cloudinary Python SDK (Django)
Hi everyone, I was reading through the documentation and didn't manage to find what I was looking for (or maybe I'm missing something).

First of all, let me briefly explain my situation:
Django project (v3.2.9), and a basic Photo model (same as the examples in the docs) with the CloudinaryField.
What I'm trying to achieve is to be able to specify an upload folder for **all** the media uploaded inside my Django project, something like `mywebsite_com/some_image.jpg`.

I've seen issues treating this situation, and the proposed solution was a **ModelForm** with the folder option specified for the CloudinaryFileField, see example code below.

```py
# models.py
from django.db import models
from cloudinary.models import CloudinaryField

class Photo(models.Model):
  image = CloudinaryField('image')
```
```py
# forms.py
from django.forms import ModelForm      
from cloudinary.forms import CloudinaryFileField      
from .models import Photo

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = '__all__'

    image = CloudinaryFileField(
        options = { 
            'folder': 'mywebsite_com',
        })
```
```py
# admin.py
from django.contrib import admin
from .models import Photo
from .forms import PhotoForm

@admin.register(Photo)
class PhotoAdmin(admin.ModelAdmin):
    form = PhotoForm
```

**This works, but here's my doubt:**

In `settings.py` I placed the `CLOUDINARY = { ... }` dict with the authentication parameters, and that (according to the [docs](https://cloudinary.com/documentation/cloudinary_sdks#configuration_parameters)) should accept a `upload_preset` field pointing to an Upload Preset created on Cloudinary (where I specified a folder, along with file naming rules etc...).
I tried it, sure that it would apply to all Cloudinary-related stuff I do inside my project, **but it does not**.

```py
# settings.py
CLOUDINARY = {
  'cloud_name': 'name',  
  'api_key': '123123123123',  
  'api_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secure': True,
  'upload_preset': 'mywebsite_com',  # <-- Not working
}
```

I can specify the `upload_preset` in the ModelForm like this and it works as intended:
```py
# forms.py
from django.forms import ModelForm      
from cloudinary.forms import CloudinaryFileField      
from .models import Photo

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = '__all__'

    image = CloudinaryFileField(
        options = { 
            'upload_preset': 'mywebsite_com',  # That's the name of my upload preset on Cloudinary
        })
```

### So here's the actual question:
Shouldn't `CloudinaryField` automatically inherit general options like this one from the `CLOUDINARY` config placed inside `settings.py`? Or am I missing the correct section of the documentation?

Thanks in advance for the good work!

**Comment by Vdeub-cloudinary** [comment]
Hi @Hecsall, 
This is not supported for backend SDKs, that's the reason you can't set it up. 
I have raised a feature request in order to add this for backend SDKs. You can still use your workaround for the time being.

**Comment by Hecsall** [comment]
I see, thank you for the answer.
I'll stick with that approach, then.
