### ISSUE TITLE
set fl_progressive flag in build_url

### ISSUE THREAD

**Issue by kirantyefun** [cloudinary/pycloudinary#303]
# Feature request for Cloudinary Python SDK
…(If your feature is for other SDKs, please request them there)

## Explain your use case
… i need to load my images in a progressive way that cloudinary  supports.

## Describe the problem you’re trying to solve
I could not find any documentation related to how I can add the fl_progressive flag in the CloudinaryImage.build_url api.

## Do you have a proposed solution?
… NO. if there's any implementation regarding it. Please provide to me.

**Comment by Vdeub-cloudinary** [comment]
Hi @kirantyefun,

Here is the right syntax:
```
cloudinary.CloudinaryImage("sample.jpg").build_url(flags="progressive")
### output: http://res.cloudinary.com/demo/image/upload/fl_progressive/sample.jpg
```

**Comment by kirantyefun** [comment]
Thanks @Vdeub-cloudinary for the quick response. Got what i needed.
