### ISSUE TITLE
Exceptions raised when pycloudinary is not configured are impossible to catch with granularity

### ISSUE THREAD

**Issue by andrewsg** [cloudinary/pycloudinary#32]
When Cloudinary is not configured, for instance because cloud_name is not included in the configuration or so forth, pycloudinary raises Exception().  This is impossible to catch and separate out from any other type of Exception subclass, so it can't be handled safely in a try/except block without risking accidentally catching termination signals, IOError, etc.

I am trying to build a reusable app with a graceful fail if the user does not have a Cloudinary account, so I would like to be able to catch this exception.  In general, raising a bare Exception() instead of some kind of subclass (I think a ValueError might be appropriate in this kind of situation, but a custom subclass could work too) is not best practice in Python, largely for this reason.

I think the problem could be minimally solved by changing every instance of Exception() in the code to ValueError(), or alternatively a custom Exception subclass.  This change would be backwards-compatible because anyone who is already trying to catch a bare Exception (which is not a good idea!) should also catch ValueError successfully.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
