### ISSUE TITLE
How to get the name of the image file

### ISSUE THREAD

**Issue by kailashchoudhary11** [cloudinary/pycloudinary#332]
how can i get the name of the image uploaded?

**Comment by tamaracloudinary** [comment]
Hi there, 

The name of the image is its Public ID in Cloudinary. You can get it as part of the response to your upload.
If you don't supply a Public ID in the upload API call, you will receive a randomly assigned Public ID in the response from the upload API call. A randomly generated public_id looks something like this: `8jsb1xofxdqamu2rzwt9q`. The resulting delivery URL for such an asset would be something like:

https://res.cloudinary.com/demo/image/upload/8jsb1xofxdqamu2rzwt9q.jpg

Here's a sample response of a raw upload call, which is slightly different from an image or video upload response (https://cloudinary.com/documentation/upload_images#upload_response):

{
 "public_id": "sample_spreadsheet.xls",
 "version": 1371928603,
 "signature": "9088291a2c12202767cfa7c5e874afee72be78cd",
 "resource_type": "raw",
 "created_at": "2017-06-22T19:16:43Z",
 "tags": [],
 "bytes": 6144,
 "type": "upload",
 "etag": "107bf134b5afd11cc7544d60108d87b", 
 "url": "http://res.cloudinary.com/demo/raw/upload/v1371928603/sample_spreadsheet.xls",
 "secure_url": "https://res.cloudinary.com/demo/raw/upload/v1371928603/sample_spreadsheet.xls"
 "original_filename": "sample_spreadsheet"
}

Hope this helps, please let me know if you have any further questions. 

Best regards, 
Tamara

**Comment by kailashchoudhary11** [comment]
@tamaracloudinary Thank you! But it is not giving me the exact name which is given while uploading the file

**Comment by tamaracloudinary** [comment]
@kailashchoudhary11 Can you please share the URL or the Public ID and your cloud name so I can take a look in our logs?
Thanks
-Tamara

**Comment by tamaracloudinary** [comment]
@kailashchoudhary11 Do you have an update? :)

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 Do you have an update? :)

Oh, It was fixed way back. Sorry for not informing you hehe :)

**Comment by tamaracloudinary** [comment]
@kailashchoudhary11 Thanks for the update, I'll close the ticket :)
Have a good one!
