### ISSUE TITLE
Not compatible with urllib3 v2

### ISSUE THREAD

**Issue by salomvary** [cloudinary/pycloudinary#355]
## Describe the bug in a sentence or two.

[urllib3 2.0.0 was released on 2023-04-26](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#200-2023-04-26) but pycloudinary has not yet been updated to be compatible with it.

To make things worse, pycloudinary was only marked as not compatible with urllib3 2.x in 1.29.0 (3ec8cd1dfb9d9fa012cf73a54dc396a1c6d51326) meaning that dependency managers might force an older pycloudinary version when latest urllib3 is used, but that only results in runtime errors in pycloudinary.

Ideally using latest pycloudinary and latest urllib3 should be possible.

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [ ] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [x] Other: compatibility

## Error screenshots or Stack Trace (if applicable)
```
$ poetry update cloudinary 
Package operations: 0 installs, 2 updates, 0 removals

  • Updating urllib3 (2.0.4 -> 1.26.16)
  • Updating cloudinary (1.28.1 -> 1.34.0)

$ poetry update urllib3   
Package operations: 0 installs, 2 updates, 0 removals

  • Updating urllib3 (1.26.16 -> 2.0.4)
  • Updating cloudinary (1.34.0 -> 1.28.1)
```

## Operating System
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [x] All

## Environment and Frameworks (fill in the version numbers)

- Cloudinary Python SDK version - 1.34.0
- Python Version - 3.11
- Framework (Django, Flask, etc) - n/a

**Comment by JanBeelte** [comment]
+1 for this issue.
It is currently not possible to use cloudinary and google cloud in one project:
```
The conflict is caused by:
    The user requested urllib3
    cloudinary 1.35.0 depends on urllib3<2 and >=1.26.5
    google-auth 2.23.1 depends on urllib3>=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
Feels like a blocker for many applications.

**Comment by tommyg-cld** [comment]
@salomvary @JanBeelte thx, we are checking and will keep you posted.
