### ISSUE TITLE
Migrate test suite to pytest

### ISSUE THREAD

**Issue by ThexXTURBOXx** [cloudinary/pycloudinary#368]
Taken from #367

It might be worth considering to migrate to `pytest` in the near future as suggested [here](https://app.travis-ci.com/github/cloudinary/pycloudinary/jobs/611271154#L283).
The changes should only be rather minimal, but it might be tricky to simultaneously get Python 2.7 and 3.x working.

**Comment by const-cloudinary** [comment]
@ThexXTURBOXx , that's a great idea!

**Comment by kurayami07734** [comment]
May I work on this ?

**Comment by const-cloudinary** [comment]
@kurayami07734 , sure

**Comment by kurayami07734** [comment]
I looked at the docs for pytest
[They require python 3.7+](https://docs.pytest.org/en/7.1.x/index.html)

**Comment by ThexXTURBOXx** [comment]
@kurayami07734 Older versions of pytest work for Python 2.7 and older 3.x releases: https://docs.pytest.org/en/6.2.x/py27-py34-deprecation.html

**Comment by kurayami07734** [comment]
I'm getting this error when trying to run the `test_config.py` test after editing it for pytest
![screenshot-2023-10-20_21:37:03](https://github.com/cloudinary/pycloudinary/assets/60501848/cacf5840-0c0f-4049-a150-d8b7f9d29065)

**Comment by ThexXTURBOXx** [comment]
The test suite should be runnable through tox, I would guess

**Comment by kurayami07734** [comment]
where in the `test_archive.py` file is the api_key set?
