### ISSUE TITLE
add styles to {% cloudinary image width=100 height=100 crop="fill" %}  

### ISSUE THREAD

**Issue by dev-yohan** [cloudinary/pycloudinary#38]
Hi we need to set the width of the image in 100%, how can i do this???

**Comment by taragano** [comment]
You can do something like:

    src,options = cloudinary.CloudinaryImage("my_image.jpg").image(width = 100,  height = 100,  crop = "fill")
and then do:

    <img src="{{ src }}" width="100%" />
or:

    <img src="{{ src }}" style="width: 100%" />
Having said that, we recommend you to check out and use our responsive support which should answer your requirements 
http://cloudinary.com/blog/how_to_automatically_create_images_for_responsive_design

**Comment by dev-yohan** [comment]
great! thanks  a lot
