### ISSUE TITLE
Reference documentation

### ISSUE THREAD

**Issue by alexpirine** [cloudinary/pycloudinary#392]
Hello,

Do you have some reference documentation for this Python library?

There are examples, videos and tutorials in [the documentation](https://cloudinary.com/documentation/django_integration) but I wish I had access to a reference API documentation with all the available options.

For instance, what settings is `cloudinary.config` supporting? There are some documented settings like `cloud_name`, `api_key`, `api_secret`, but what other options are available? I see some other options used throughout the code, like `secure`, `use_cache`, `oauth_token`, and so on.

Another example: `cloudinary.uploader.upload` seems to accept a path on the local file system, but also File-like object, or a URL… Where can I read about the accepted types and arguments of `cloudinary.uploader.upload`?

**Comment by dannyv-cloudinary** [comment]
Hi @alexpirine.

We don't have a documented list of these parameters, however they should be exposed in your IDE's autocomplete. The properties are:

- cloud_name
- api_key
- api_secret
- api_proxy
- private_cdn
- secure_distribution
- force_version
- ssl_detected
- secure
- cdn_subdomain
- secure_cdn_subdomain
- cname
- shorten
- sign_url
- long_url_signature
- use_root_path
- auth_token
- account_id
- provisioning_api_key
- provisioning_api_secret
- oauth_token

- *

**Comment by const-cloudinary** [comment]
@alexpirine , you can check our documentation:
https://cloudinary.com/documentation/cloudinary_sdks#configuration_parameters

Regarding upload parameters:
https://cloudinary.com/documentation/image_upload_api_reference#upload_required_parameters

There is also a great community support forum:
https://community.cloudinary.com/

Hope it is helpful.

**Comment by alexpirine** [comment]
Thank you. Yes, I am able to figure out how to use the library by looking at examples and by checking the source code.

I just wish there was a reference documentation for the Python API, just like for the [Go](https://pkg.go.dev/github.com/cloudinary/cloudinary-go@v1.7.0/api/uploader#API.Upload) or [PHP](https://cloudinary.com/documentation/sdks/php/Cloudinary/Api/Upload/UploadApi.html#method_upload) SDKs — that would help me to quickly verify the expected data types and structures, instead of checking the source code or searching for similar examples elsewhere and hoping that the Python API didn't change from the time the given example was written.

But no big deal, I understand you don't provide it at the moment.

**Comment by alexpirine** [comment]
> Hi @alexpirine.
> 
> We don't have a documented list of these parameters, however they should be exposed in your IDE's autocomplete.

@dannyv-cloudinary what IDE are you using and how do you configure it to show the autocomplete?

Here is Visual Studio Code with Pylance:

<img width="493" alt="image" src="https://github.com/cloudinary/pycloudinary/assets/1610035/0507a727-beeb-46c6-a675-5aad023b1758">

**Comment by dannyv-cloudinary** [comment]
Please accept my apologies, @alexpirine. I typically work with our Node SDK which does work with sutocomplete out-of-the-box, and assumed our Python SDK worked the same way.
I'm afraid I'm not sure if it's possible to autocomplete in the IDE, but I see my colleague has included some useful documentation links above for your reference.
