### ISSUE TITLE
Create New Sample Project with Generative AI and Special Use Cases

### ISSUE THREAD

**Issue by const-cloudinary** [cloudinary/pycloudinary#401]
We're looking to enhance our sample projects and we need your help! By creating a new sample project, this is your chance to contribute to our SDKs and showcase the power of **Cloudinary**.

**Here’s what we’re looking for:**

- Create a new sample project with the repository's SDK
- Incorporate generative AI transformations for media (e.g., automatic content creation, enhancements).
- Showcase special use cases for Cloudinary, like personalized media workflows, complex video transformations, or innovative media delivery strategies.
- The sample project shouldn't have excessive dependencies or complexity

This is a great opportunity to experiment and show your creativity with Cloudinary's SDKs and contribute to something impactful.

**Comment by theperiperi** [comment]
Hey I'm willing to contribute, can you assign the issue to me?

**Comment by theperiperi** [comment]
Hey, I finished the PR, but there's two things:

The Travis build fails for the PR for some reason, I think that's some internal issue

And also can this PR be assigned to me under hacktoberfest?

**Comment by michal-sordyl-cloudinary** [comment]
@theperiperi Thank you for the contribution, we will review your PR

**Comment by codingis4noobs2** [comment]
Hello @michal-sordyl-cloudinary , I have also created a Cloudinary Powered app that Uses its Gen AI transformations. Can I create a new issue? You can find my app here: https://github.com/codingis4noobs2/Cloudinary-spoooky-Hackathon

**Comment by michal-sordyl-cloudinary** [comment]
@codingis4noobs2 Yes, please create a new issue. The effect is worth that!
FYI @const-cloudinary
