### ISSUE TITLE
Gravatar Support

### ISSUE THREAD

**Issue by vinezhu** [cloudinary/pycloudinary#43]
Hi Cloudinary Gravatar,

I'm asking for a gravatar support how it already exists in the ruby libary.

Thanks for your help!

**Comment by taragano** [comment]
You can set the `type` parameter to `gravatar`. e.g.,:

    cloudinary.CloudinaryImage("e3264cf16f34ecd3c7c564f5668cbc1e.jpg", type = 'gravatar').image()

**Comment by vinezhu** [comment]
Thanks a lot for your reply.
The only difference left is that you can add directly the email address.
```
<%= gravatar_profile_image_tag("info@cloudinary.com", :width => 150, :height => 150) %>
```
