### ISSUE TITLE
django rest framework implementation

### ISSUE THREAD

**Issue by rustanacexd** [cloudinary/pycloudinary#51]
any guide for django rest framework?

**Comment by thedrow** [comment]
Just use the ImageField. It works.

**Comment by ckaalund** [comment]
Not totally. Example setting use_url=False returns error: 'CloudinaryResource' object has no attribute 'name'

Model serializer returns different value (image/upload/v143775/iqctokqk4yesrm.jpg) compared to setting image = serializers.ImageField() that returns full url.

**Comment by djq** [comment]
This is definitely still a problem. For example, if you use a `Charfield` to store the `public_id`, the Cloudinary library is prepending the `public_id` with `image/upload`. Then, when you use the `.build_url()` function it generates a url with two copies of `image/upload`. 

For example this is the output of `build_url()` 

    http://res.cloudinary.com/<account>/image/upload/v1/image/upload/<public_id>

**Comment by rustanacexd** [comment]
still not solved right?

**Comment by tocker** [comment]
@rustanacexd @djq @ckaalund Checkout the new 1.5.0 release.
If this is still an issue, please contact us at https://support.cloudinary.com/hc/en-us/requests/new so we can resolve the issue.

(Ideally, add a test to `django_tests` folder so we can reproduce it. 😄 )

**Comment by saschwarz** [comment]
There really needs to be an example of how to use Django Rest Framework and JSON payloads (not form POST) to upload an image to Cloudinary and store the result in a `CloudinaryField`. This seems to do the right thing: https://stackoverflow.com/a/46946933/457935

**Comment by roeeba** [comment]
Hi @saschwarz, Appreciate the feedback. I'll open an internal ticket regarding this so the team could review your suggestion. Thanks!

**Comment by justincohan** [comment]
Was having trouble getting an upload that worked with DRF and ImageField to work the same with CloudinaryField. Adding `parser_classes = (MultiPartParser,)` to my view worked.  I found that through this guide.  

https://ubaydah.hashnode.dev/implementing-api-in-django-rest-framework-to-upload-and-store-images-in-cloudinary

**Comment by tommyg-cld** [comment]
@justincohan thx for letting us know! if you need anything else in the meantime, let us know
