### ISSUE TITLE
CloudinaryField max_length needs to be specified

### ISSUE THREAD

**Issue by wli** [cloudinary/pycloudinary#53]
It looks like the max_length=100 restriction was removed in version 1.1.2, but it seems to cause problems for a new model migration. I'm running Django 1.8.2, Python 3.4.3, cloudinary 1.1.2.

Relevant commit: https://github.com/cloudinary/pycloudinary/commit/73abd59ad7ff78ea0f44a19b557fb75128d8dbcf

Error trace:
````
  Applying photos.0001_initial...Traceback (most recent call last):
  File "/home/wli/projects/hiking/.venv/lib/python3.4/site-packages/django/db/ba
ckends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: syntax error at or near "None"
LINE 1: ..."id" serial NOT NULL PRIMARY KEY, "image" varchar(None) NOT ...
````

Here's the relevant model file:
````
 from cloudinary.models import CloudinaryField
 from django.db import models


 class Photo(models.Model):
     image = CloudinaryField('image')
````

and the migration that it generated, which failed:
````
 from __future__ import unicode_literals

 from django.db import models, migrations
 import cloudinary.models


 class Migration(migrations.Migration):

     dependencies = [
     ]

     operations = [
         migrations.CreateModel(
             name='Photo',
             fields=[
                 ('id', models.AutoField(verbose_name='ID', auto_created=True, serialize=False, primary_key=True)),
                 ('image', cloudinary.models.CloudinaryField(verbose_name='image')),
             ],
         ),
     ]
````

**Comment by wli** [comment]
Here's a quick documentation update that fixed my problem: https://github.com/cloudinary/pycloudinary/pull/54

Please let me know if I'm understanding this wrong.

**Comment by tocker** [comment]
Hi @wli ,

Thanks for the detailed description and the pull request.
max_length was brought back the model in version 1.1.3.

Please update and retest. 

The changes are different from your PR, so I will close it - but thanks for the effort!

**Comment by wli** [comment]
Thanks for fixing this, @tocker. I'm going to close this ticket since it looks resolved.
