### ISSUE TITLE
Cloudinaryfield in v1.1.2, public_id and failed migrations in django

### ISSUE THREAD

**Issue by danialt** [cloudinary/pycloudinary#55]
I've been using cloudinary since long time, and recently noticed that the image field in database in not homogeneous, sometimes it is xxxx/xxx.jpg and /image/upload/xxx/xxx.png, and this has caused headaches.

Now, I updated to 1.1.2 and the migration fails, since the max_length is missing from the CloudinaryField, I added it there and the migration runs, but keeps saying that there is a new migration, and again puts image fields there without max_length. So, there is no way out of it I guess.

Is there a solution to this?

**Comment by taragano** [comment]
Regarding the migration - Please update to the latest version (v.1.1.3) and let me know if this is fixed for you now?
Regarding the image fields differences, can you please share some more information regarding what issues this may cause for you? They should both work successfully.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
