### ISSUE TITLE
Question - Are videos in CloudinaryField supported?

### ISSUE THREAD

**Issue by bufke** [cloudinary/pycloudinary#63]
I see the docs show it with image `CloudinaryField('image')` but what is that string 'image' for? Can I pass other things in - specifically video?

**Comment by bufke** [comment]
I can answer my own question. It can be done like this

```
video = CloudinaryField(resource_type='video')
```

Perhaps the docs should be updated to show an example? Of note you can't just do `CloudinaryField('video')` which one might assume from the example in the docs.

http://cloudinary.com/documentation/django_image_upload#django_forms_and_models

**Comment by taragano** [comment]
Thank you for the update, I'm glad you've found the solution. I've passed it on to our team to make our documentations clearer about this matter.
I'll be closing this issue for now, please re-open it if you need any further assistance.
