### ISSUE TITLE
can't list video resources

### ISSUE THREAD

**Issue by streamgao** [cloudinary/pycloudinary#64]
when i was trying to see video resource details. i always get the problem:

  File "uploader.py", line 151, in <module>
    result = cloudinary.api.resources_by_tag("in and out")
  File "/usr/local/lib/python2.7/site-packages/cloudinary/api.py", line 55, in resources_by_tag
    return call_api("get", uri, only(options, "next_cursor", "max_results", "tags", "context", "moderations", "direction"), **options)
  File "/usr/local/lib/python2.7/site-packages/cloudinary/api.py", line 260, in call_api
    raise GeneralError("Error parsing server response (%d) - %s. Got - %s" % (response.code, body, e))
cloudinary.api.GeneralError: Error parsing server response (400) - . Got - No JSON object could be decoded

cloudinary.api.resources cannot access video files, even you signed the resrouce type to be raw.

**Comment by MaorGar** [comment]
Hi @streamgao,

To list videos by tag, add the `resource_type` flag to your API call - 
```
result = cloudinary.api.resources_by_tag("tag_name", resource_type = 'video')
```
And using this call - 
```
result = cloudinary.api.resources(resource_type = 'video')
```
will return video resources, regardless of tags.

You can find more information about the admin API  in this link - 
http://cloudinary.com/documentation/admin_api

**Comment by MaorGariv** [comment]
Hi,

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
