### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by danleyb2** [cloudinary/pycloudinary#67]
i keep getting this warning even though everything works fine

```
python/lib/python2.7/site-packages/cloudinary/models.py:24: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)
```

**Comment by avorio** [comment]
Same here. It would be great to have this fixed.

**Comment by jdotjdot** [comment]
With the [release](https://docs.djangoproject.com/en/1.10/ref/templates/upgrading/) of Django 1.10, this no longer works fine and is in fact a failing error that prevents servers from running.

**Comment by taragano** [comment]
Hi all,

Thank you for your reports. We'll be taking a close look at this and we'll update as soon as possible.

**Comment by olcay** [comment]
Hi, I updated the django to 1.10 and now I can't use cloudinary. Please, fix this issue as mentioned below.

https://docs.djangoproject.com/en/1.10/releases/1.8/#subfieldbase

**Comment by avinash011** [comment]
Can anybody from cloudinary team can help in this ? 
I just changed from this to below and worked
class CloudinaryField(with_metaclass(models.SubfieldBase, models.Field)):
class CloudinaryField(models.Field):

**Comment by avinash011** [comment]
if django.VERSION > (1, 10):
   HashFieldBase = models.Field
else:
   HashFieldBase = with_metaclass(models.SubfieldBase, models.Field)

#class CloudinaryField(with_metaclass(models.SubfieldBase, models.Field)):
class CloudinaryField(HashFieldBase):

**Comment by godshall** [comment]
Here's a quick fix I threw together for an existing project that I wanted to upgrade to Django 1.10.  I have not thoroughly tested it, but it seems to work well so far.  Additional work would need to be done to make it compatible with previous versions of Django.  I wanted to make it available in case anyone found it helpful.

https://github.com/sewdigital/pycloudinary/commit/8bf46f88b62670b13b11a4928fe773317587ff30

**Comment by wojtek-fliposports** [comment]
Fix for @avinash011 will not work properly.
Better approach:


```python
import django

if django.VERSION >= (1, 10):
    class HashFieldBase(models.Field):
        def from_db_value(value, *args, **kwargs):
            return self.to_python(value)
else:
    HashFieldBase = with_metaclass(models.SubfieldBase, models.Field)

#class CloudinaryField(with_metaclass(models.SubfieldBase, models.Field)):
class CloudinaryField(HashFieldBase):

```

**Comment by wli** [comment]
@tocker @ronen-burin - just checking in to whether this will be released to PyPi anytime soon? The latest released version is 1.4.0 from June 2016. Thanks!

**Comment by benjigoldberg** [comment]
@tocker @ronen-burin this is a critical patch for a number of users of this library, when can we expect a release / what can the community do to help?

**Comment by quinn** [comment]
@cloudinary  for the love of god just update to pypi ???? this has been merged. it's fixed. all you have to do is push. this is pretty bad for a pay-for service with salaried developers (i'm assuming..)

Also, upgrade to a github org account? @cloudinary is a user ? what kind of op are you kids running over there * smh *

**Comment by tocker** [comment]
@quinn @benjigoldberg pypi will be updated this weekend. We realize this is long anticipated but wanted to make sure the support for python 3 / Django 1.10 doesn't break compatibility with older version which our customers are still using.

@quinn you are absolutely right about the @cloudinary account and it is was indeed scheduled to migrate to an organization account.

**Comment by benjigoldberg** [comment]
@tocker thanks much, I/we appreciate the pending release to PyPi

**Comment by tocker** [comment]
PyPi has been updated with version 1.5.0.
