### ISSUE TITLE
CloudinaryFileField In Admin Causing Errors

### ISSUE THREAD

**Issue by akath20** [cloudinary/pycloudinary#68]
class UserAdminForm(forms.ModelForm):
        def __init__(self, *args, **kwargs):
		    super(UserAdminForm, self).__init__(*args, **kwargs)
		    try:
			    username = self.instance.username
		    except:
			    username = "unknow"
		
		    self.fields['image'] = CloudinaryFileField(
			    options = {
				    "public_id" : 'users/' + username + '/profile'
			    }
		    )

This is the custom Form. When I save it it says "Please correct the error below." but doesn't show the error.

**Comment by roeeba** [comment]
Hi @akath20 , sorry for the delayed response. I see that our support team has assisted with your issue on a direct support ticket. Let us know if you need anything else?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
