### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by km-pg** [cloudinary/pycloudinary#72]
This site is reporting that the cloudinary library doesn't support python 3.
https://caniusepython3.com/project/cloudinary

It probably does though. I think you just need to update setup.py to include this:
"Programming Language :: Python :: 3"

**Comment by alex7217** [comment]
Looking to try this service out today.

I just rechecked https://caniusepython3.com/project/cloudinary

They report "No blockers for your transition to Python 3", unsure what the original support issue in this github issue was about. Hope that helps the next guy.

**Comment by km-pg** [comment]
@alex7217 Huh, I wonder what changed. The cloudinary package still doesn't seem to meet any of the requirements listed here:
https://github.com/brettcannon/caniusepython3#how-do-you-tell-if-a-project-has-been-ported-to-python-3

**Comment by tocker** [comment]
Python 3 and Django 1.10 compatibility in currently in the works.

**Comment by tocker** [comment]
@km-pg @alex7217 - thanks for your suggestions!
We updated the `setup.py` script to include the classification.

**Comment by km-pg** [comment]
Thanks!
