### ISSUE TITLE
MultiMediaField model CloudinaryField 

### ISSUE THREAD

**Issue by sagoyanfisic** [cloudinary/pycloudinary#73]
There is a way to use multiple fields in an image field to upload my django admin?

**Comment by taragano** [comment]
Hi @sagoyanfisic,

Yes, there is. Please see:
https://support.cloudinary.com/hc/en-us/articles/202519962-Can-I-have-multiple-upload-fields-on-the-same-page-

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
