### ISSUE TITLE
Use of os.fstat will fail for unflushed files

### ISSUE THREAD

**Issue by frankier** [cloudinary/pycloudinary#78]
MultipartParam uses fstat to determine the size of a file object here: https://github.com/cloudinary/pycloudinary/blob/f98baf3a45f842e0106646429f1e2bf10c2e309a/cloudinary/poster/encode.py#L138

This will only work for files which have been flush(). Other files can have buffered changes which are not yet visible to the operating system. The alternative approach of using

```
fileobj.seek(0, 2)
self.filesize = fileobj.tell()
fileobj.seek(0)
```

will always succeed, even for unflushed files. Is there any disadvantage to getting rid of fstat and replacing it with seek/tell? I believe this would help to make the library more robust.

**Comment by tocker** [comment]
@frankier in version 1.5.0 we replaced poster with urllib3. Can you please update and retest?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
