### ISSUE TITLE
There is a way to use multiple fields in an image field to upload my django admin?

### ISSUE THREAD

**Issue by sagoyanfisic** [cloudinary/pycloudinary#79]
Please

**Comment by taragano** [comment]
If you refer to having multiple upload fields on the same page, please have a look at the following:
https://support.cloudinary.com/hc/en-us/articles/202519962-Can-I-have-multiple-upload-fields-on-the-same-page-

Let me know if this answers your question?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
