### ISSUE TITLE
Draft a new release - Django10 Support

### ISSUE THREAD

**Issue by leonardocintra** [cloudinary/pycloudinary#80]
Draft a new release by #69 

## Error:
![image](https://cloud.githubusercontent.com/assets/5832193/20368697/48941114-ac3c-11e6-8ff9-f0b854e5c806.png)

**Comment by nadavofi** [comment]
Hi Leonardo, please check out our recent release:
https://github.com/cloudinary/pycloudinary/releases/tag/1.5.0

**Comment by leonardocintra-luizalabs** [comment]
@nadavofi thank you!
👍
