### ISSUE TITLE
Exception handling with djangoREST framework

### ISSUE THREAD

**Issue by rajeshbk042** [cloudinary/pycloudinary#85]
Hi All,

How can we handle exceptions and failed upload images?

I need to handle all the exception that occurs when uploading images to cludinary and retry upload with failed uploaded images.

Please help me and give me the possible error response from cloudinary with django.

Thanks

**Comment by roeeba** [comment]
Hi @rajeshbk042 You can set a webhook for your upload process by adding the `notification_url` parameter to your upload request. Fore more information: http://cloudinary.com/blog/webhooks_upload_notifications_and_background_image_processing.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
