### ISSUE TITLE
Using unicode literals in config causes UnicodeDecodeError on upload

### ISSUE THREAD

**Issue by mikecodona** [cloudinary/pycloudinary#87]
If the `CLOUDINARY` settings are defined in a python file which uses unicode literals (or if the `cloud_name` is defined as a unicode literal manually) there is an error thrown deep down inside `httplib.py`. The reason for this is that `cloudinary_api_url` joins together all of the url parts which, if one of these elements is unicode, generates a URL which is a unicode string.

```
In [1]: "/".join(('non-unicode', u'unicode'))
Out[1]: u'non-unicode/unicode'
```

There was a python bug raised for this here https://bugs.python.org/issue11898 but it looks like it was treated as an invalid input. I guess you could say the same thing here and that passing a unicode string is undefined behaviour but at least this bug might help someone else with this problem.

**Comment by roeeba** [comment]
Hi @mikecodona, Thanks for the detailed report! Our general practice is usually to pass input data to httplib unchanged, so in case of an error, the user will get a familiar error message. In this case, though, it might actually be better to cover for httplib since (looking at the link you've attached) it is confusing even to httplib users. We will add this issue to our backlog.

**Comment by rubengrill** [comment]
I have the same problem (python 2.7.13). I wanted to upload a video and for this I defined a `CloudinaryField(resource_type='video')`, with `from __future__ import unicode_literals`, so it is `u'video'`.
Now when cloudinary assembles the url in `cloudinary_api_url` (https://github.com/cloudinary/pycloudinary/blob/1.8.0/cloudinary/utils.py#L460) , the complete url is suddenly a unicode string (as @mikecodona mentioned).
This causes an error in httplib, when the header is concatenated with the message_body (also as @mikecodona mentioned).

As the comments in the httplib bug issue state, httplib expects url to be of type `str`, so wouldn't it be appropriate to cast the final result in `cloudinary_api_url` to `str`?

My workaround was to define `CloudinaryField(resource_type=b'video')`, then it worked.

Here the "stacktrace" for easier understanding:
- https://github.com/cloudinary/pycloudinary/blob/1.8.0/cloudinary/models.py#L85 (generating options)
- https://github.com/cloudinary/pycloudinary/blob/1.8.0/cloudinary/models.py#L87 (Calling `uploader.upload_resource`)
- https://github.com/cloudinary/pycloudinary/blob/1.8.0/cloudinary/uploader.py#L222 (Generating the url via `utils.cloudinary_api_url`)
- https://github.com/cloudinary/pycloudinary/blob/1.8.0/cloudinary/uploader.py#L257 (Handing over to httplib)
