### ISSUE TITLE
TemplateSyntaxError at /blog/

### ISSUE THREAD

**Issue by Sambeth** [cloudinary/pycloudinary#97]
I get this error from my template when I input `{% load cloudinary %}
`

> TemplateSyntaxError at /blog/
> 'cloudinary' is not a registered tag library. Must be one of:
> addthis
> admin_list
> admin_modify
> admin_static
> admin_urls
> cache
> i18n
> l10n
> log
> markdown_deux_tags
> static
> staticfiles
> tz

**Comment by MaorGariv** [comment]
Hi,

Have you added `cloudinary` to your list of `INSTALLED_APPS`in settings.py?

**Comment by Sambeth** [comment]
yeah i did that and was giving me an error but it disappeared after sometime...it works now....it wasn't part of the documentation even though its pretty obvious to always add installed apps to the settings.py...

**Comment by MaorGariv** [comment]
Thanks for the update. Great to hear it's working for you now :)

**Comment by pawar-a** [comment]
> yeah i did that and was giving me an error but it disappeared after sometime...it works now....it wasn't part of the documentation even though its pretty obvious to always add installed apps to the settings.py...

hyy i have same error facing in django . so what i can do for solve this error

**Comment by momoip** [comment]
Hi,
Have you checked if cloudinary is added to your list of INSTALLED_APPS in settings.py?

**Comment by WillamysC** [comment]
> > yeah i did that and was giving me an error but it disappeared after sometime...it works now....it wasn't part of the documentation even though its pretty obvious to always add installed apps to the settings.py...
> 
> hyy i have same error facing in django . so what i can do for solve this error

hy. I have this same error, have you succeeded to solve it?

**Comment by atdcloud** [comment]
> Add `cloudinary` to your list of `INSTALLED_APPS` in settings.py
